version: '3.7'

services:
  geo-webgis:
    container_name: webgis
    image: nginx:1.16.0-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.template
      - ./build:/usr/share/nginx/html
    environment:
      - MAP_TILES_API=10.1.8.130:9090
      - GEO_API=10.1.8.130:5000
    command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
